services:
  node-example:
    container_name: distroless-getsecret
    ports:
       - "80:80"
    secrets:
      - THEPASSWORD1
      - THEPASSWORD2
    build:
      context: .
    image: "distroless-getsecret:1"
secrets:
  THEPASSWORD1:
    file: ./.secrets/THEPASSWORD1
  THEPASSWORD2:
    file: ./.secrets/THEPASSWORD2

